#ifndef GUARD_HOLD_EFFECTS_H
#define GUARD_HOLD_EFFECTS_H

#define HOLD_EFFECT_NONE            0
#define HOLD_EFFECT_RESTORE_HP      1
#define HOLD_EFFECT_CURE_PAR        2
#define HOLD_EFFECT_CURE_SLP        3
#define HOLD_EFFECT_CURE_PSN        4
#define HOLD_EFFECT_CURE_BRN        5
#define HOLD_EFFECT_CURE_FRZ        6
#define HOLD_EFFECT_RESTORE_PP      7
#define HOLD_EFFECT_CURE_CONFUSION  8
#define HOLD_EFFECT_CURE_STATUS     9
#define HOLD_EFFECT_CONFUSE_SPICY  10
#define HOLD_EFFECT_CONFUSE_DRY    11
#define HOLD_EFFECT_CONFUSE_SWEET  12
#define HOLD_EFFECT_CONFUSE_BITTER 13
#define HOLD_EFFECT_CONFUSE_SOUR   14
#define HOLD_EFFECT_ATTACK_UP      15
#define HOLD_EFFECT_DEFENSE_UP     16
#define HOLD_EFFECT_SPEED_UP       17
#define HOLD_EFFECT_SP_ATTACK_UP   18
#define HOLD_EFFECT_SP_DEFENSE_UP  19
#define HOLD_EFFECT_CRITICAL_UP    20
#define HOLD_EFFECT_RANDOM_STAT_UP 21
#define HOLD_EFFECT_EVASION_UP     22
#define HOLD_EFFECT_RESTORE_STATS  23
#define HOLD_EFFECT_MACHO_BRACE    24
#define HOLD_EFFECT_EXP_SHARE      25
#define HOLD_EFFECT_QUICK_CLAW     26
#define HOLD_EFFECT_HAPPINESS_UP   27
#define HOLD_EFFECT_CURE_ATTRACT   28
#define HOLD_EFFECT_CHOICE_BAND    29
#define HOLD_EFFECT_FLINCH         30
#define HOLD_EFFECT_BUG_POWER      31
#define HOLD_EFFECT_DOUBLE_PRIZE   32
#define HOLD_EFFECT_REPEL          33
#define HOLD_EFFECT_SOUL_DEW       34
#define HOLD_EFFECT_DEEP_SEA_TOOTH 35
#define HOLD_EFFECT_DEEP_SEA_SCALE 36
#define HOLD_EFFECT_CAN_ALWAYS_RUN 37
#define HOLD_EFFECT_PREVENT_EVOLVE 38
#define HOLD_EFFECT_FOCUS_BAND     39   //Focus Sash: Item param = 100, secondaryId = 1
#define HOLD_EFFECT_LUCKY_EGG      40
#define HOLD_EFFECT_SCOPE_LENS     41
#define HOLD_EFFECT_STEEL_POWER    42
#define HOLD_EFFECT_LEFTOVERS      43
#define HOLD_EFFECT_DRAGON_SCALE   44
#define HOLD_EFFECT_LIGHT_BALL     45
#define HOLD_EFFECT_GROUND_POWER   46
#define HOLD_EFFECT_ROCK_POWER     47
#define HOLD_EFFECT_GRASS_POWER    48
#define HOLD_EFFECT_DARK_POWER     49
#define HOLD_EFFECT_FIGHTING_POWER 50
#define HOLD_EFFECT_ELECTRIC_POWER 51
#define HOLD_EFFECT_WATER_POWER    52
#define HOLD_EFFECT_FLYING_POWER   53
#define HOLD_EFFECT_POISON_POWER   54
#define HOLD_EFFECT_ICE_POWER      55
#define HOLD_EFFECT_GHOST_POWER    56
#define HOLD_EFFECT_PSYCHIC_POWER  57
#define HOLD_EFFECT_FIRE_POWER     58
#define HOLD_EFFECT_DRAGON_POWER   59
#define HOLD_EFFECT_NORMAL_POWER   60
#define HOLD_EFFECT_UP_GRADE       61
#define HOLD_EFFECT_SHELL_BELL     62
#define HOLD_EFFECT_LUCKY_PUNCH    63
#define HOLD_EFFECT_METAL_POWDER   64
#define HOLD_EFFECT_THICK_CLUB     65
#define HOLD_EFFECT_STICK          66

//NEW HOLD EFFECTS
#define HOLD_EFFECT_ROCKY_HELMET 68
#define HOLD_EFFECT_QUICK_POWDER 69
#define HOLD_EFFECT_ASSAULT_VEST 70
#define HOLD_EFFECT_EVIOLITE 71
#define HOLD_EFFECT_PLATE 72        //parameter = Move Type
#define HOLD_EFFECT_MEGA_STONE 73
#define HOLD_EFFECT_LIFE_ORB 74
#define HOLD_EFFECT_TOXIC_ORB 75
#define HOLD_EFFECT_FLAME_ORB 76
#define HOLD_EFFECT_BLACK_SLUDGE 77
#define HOLD_EFFECT_SMOOTH_ROCK 78
#define HOLD_EFFECT_DAMP_ROCK 79
#define HOLD_EFFECT_HEAT_ROCK 80
#define HOLD_EFFECT_ICY_ROCK 81
#define HOLD_EFFECT_LIGHT_CLAY 82
#define HOLD_EFFECT_WIDE_LENS 83        //parameter = % Acc Boost
#define HOLD_EFFECT_SAFETY_GOGGLES 84
#define HOLD_EFFECT_WEAKNESS_POLICY 85
#define HOLD_EFFECT_DRIVE 86        //secondaryId = Move Type
#define HOLD_EFFECT_MEMORY 87       //secondaryId = Move Type
#define HOLD_EFFECT_ADAMANT_ORB 88
#define HOLD_EFFECT_LUSTROUS_ORB 89
#define HOLD_EFFECT_GRISEOUS_ORB 90
#define HOLD_EFFECT_DESTINY_KNOT 91
#define HOLD_EFFECT_EXPERT_BELT 92
#define HOLD_EFFECT_PRIMAL_ORB 93       //Red Orb: parameter = 0, Blue Orb: parameter = 1
#define HOLD_EFFECT_GEMS 94              //secondaryId = Move Type
#define HOLD_EFFECT_RESIST_BERRY 95   //secondaryId = Move Type
#define HOLD_EFFECT_CUSTAP_BERRY 96
#define HOLD_EFFECT_LAGGING_TAIL 97
#define HOLD_EFFECT_IRON_BALL 98
#define HOLD_EFFECT_BINDING_BAND 99

#define HOLD_EFFECT_PROTECTIVE_PADS 101
#define HOLD_EFFECT_ABSORB_BULB 102
#define HOLD_EFFECT_AIR_BALLOON 103
#define HOLD_EFFECT_BIG_ROOT 104
#define HOLD_EFFECT_CELL_BATTERY 105
#define HOLD_EFFECT_EJECT_BUTTON 106
#define HOLD_EFFECT_FLOAT_STONE 107
#define HOLD_EFFECT_GRIP_CLAW 108
#define HOLD_EFFECT_LUMINOUS_MOSS 109

#define HOLD_EFFECT_METRONOME 111
#define HOLD_EFFECT_MUSCLE_BAND 112
#define HOLD_EFFECT_RED_CARD 113
#define HOLD_EFFECT_RING_TARGET 114
#define HOLD_EFFECT_SHED_SHELL 115
#define HOLD_EFFECT_SNOWBALL 116
#define HOLD_EFFECT_STICKY_BARB 117
#define HOLD_EFFECT_TERRAIN_EXTENDER 118
#define HOLD_EFFECT_WISE_GLASSES 119
#define HOLD_EFFECT_SEEDS 120               //Electric Seed: secondaryId = 1, Grassy Seed: Quality = 2, Misty Seed: Quality = 3, Psychic Seed: Quality = 4
#define HOLD_EFFECT_JABOCA_ROWAP_BERRY 121  //param = Move Split (0 = Physical, 1 = Special)
#define HOLD_EFFECT_KEE_BERRY 122
#define HOLD_EFFECT_MARANGA_BERRY 123
#define HOLD_EFFECT_ZOOM_LENS 124       //param = % Acc Boost
#define HOLD_EFFECT_ADRENALINE_ORB 125
#define HOLD_EFFECT_POWER_HERB 126
#define HOLD_EFFECT_MICLE_BERRY 127
#define HOLD_EFFECT_ENIGMA_BERRY 128
//#define HOLD_EFFECT_TYPE_BOOSTERS 129   //param = % Damage Boost
#define HOLD_EFFECT_Z_CRYSTAL 130       //secondaryId = Move Type
#define HOLD_EFFECT_EJECT_PACK 131
#define HOLD_EFFECT_ROOM_SERVICE 132
#define HOLD_EFFECT_BLUNDER_POLICY 133
#define HOLD_EFFECT_HEAVY_DUTY_BOOTS 134
#define HOLD_EFFECT_UTILITY_UMBRELLA 135
#define HOLD_EFFECT_THROAT_SPRAY 136

#define HOLD_EFFECT_COUNT   HOLD_EFFECT_THROAT_SPRAY + 1


//Choice Items
#define HOLD_EFFECT_PARAMETER_CHOICE_BAND   0
#define HOLD_EFFECT_PARAMETER_CHOICE_SPECS  1
#define HOLD_EFFECT_PARAMETER_CHOICE_SCARF  2

// Power Items
#define HOLD_EFFECT_PARAM_MACHO_BRACE   0
#define HOLD_EFFECT_PARAM_POWER_WEIGHT  1 // HP
#define HOLD_EFFECT_PARAM_POWER_BRACER  2 // Attack
#define HOLD_EFFECT_PARAM_POWER_BELT    3 // Defense
#define HOLD_EFFECT_PARAM_POWER_ANKLET  4 // Speed
#define HOLD_EFFECT_PARAM_POWER_LENS    5 // Sp Attack
#define HOLD_EFFECT_PARAM_POWER_BAND    6 // Sp Defense

//  Primal Reversions
#define HOLD_EFFECT_PARAMETER_GROUDON       0    
#define HOLD_EFFECT_PARAMETER_KYOGRE        1

// terrain seeds
#define HOLD_EFFECT_PARAMETER_ELECTRIC_SEED     1
#define HOLD_EFFECT_PARAMETER_GRASSY_SEED       2
#define HOLD_EFFECT_PARAMETER_MISTY_SEED        3
#define HOLD_EFFECT_PARAMETER_PSYCHIC_SEED      4

#endif // GUARD_HOLD_EFFECTS_H
