#ifndef GUARD_CONSTANTS_ITEMS_H
#define GUARD_CONSTANTS_ITEMS_H

#define ITEM_NONE                     0
#define ITEM_MASTER_BALL              1
#define ITEM_ULTRA_BALL               2
#define ITEM_GREAT_BALL               3
#define ITEM_POKE_BALL                4
#define ITEM_SAFARI_BALL              5
#define ITEM_NET_BALL                 6
#define ITEM_DIVE_BALL                7
#define ITEM_NEST_BALL                8
#define ITEM_REPEAT_BALL              9
#define ITEM_TIMER_BALL               10
#define ITEM_LUXURY_BALL              11
#define ITEM_PREMIER_BALL             12
// New Balls                     
#define ITEM_PARK_BALL                13
#define ITEM_CHERISH_BALL             14
#define ITEM_DUSK_BALL                15
#define ITEM_HEAL_BALL                16
#define ITEM_QUICK_BALL               17
#define ITEM_FAST_BALL                18
#define ITEM_LEVEL_BALL               19
#define ITEM_LURE_BALL                20
#define ITEM_HEAVY_BALL               21
#define ITEM_LOVE_BALL                22
#define ITEM_FRIEND_BALL              23
#define ITEM_MOON_BALL                24
#define ITEM_SPORT_BALL               25
#define ITEM_BEAST_BALL               26
#define ITEM_DREAM_BALL               27
// Medicine                      
#define ITEM_POTION                   28
#define ITEM_ANTIDOTE                 29
#define ITEM_BURN_HEAL                30
#define ITEM_ICE_HEAL                 31
#define ITEM_AWAKENING                32
#define ITEM_PARALYZE_HEAL            33
#define ITEM_FULL_RESTORE             34
#define ITEM_MAX_POTION               35
#define ITEM_HYPER_POTION             36
#define ITEM_SUPER_POTION             37
#define ITEM_FULL_HEAL                38
#define ITEM_REVIVE                   39
#define ITEM_MAX_REVIVE               40
#define ITEM_FRESH_WATER              41
#define ITEM_SODA_POP                 42
#define ITEM_LEMONADE                 43
#define ITEM_MOOMOO_MILK              44
#define ITEM_ENERGY_POWDER            45
#define ITEM_ENERGY_ROOT              46
#define ITEM_HEAL_POWDER              47
#define ITEM_REVIVAL_HERB             48
#define ITEM_ETHER                    49
#define ITEM_MAX_ETHER                50
#define ITEM_ELIXIR                   51
#define ITEM_MAX_ELIXIR               52
#define ITEM_LAVA_COOKIE              53
#define ITEM_BLUE_FLUTE               54
#define ITEM_YELLOW_FLUTE             55
#define ITEM_RED_FLUTE                56
#define ITEM_BLACK_FLUTE              57
#define ITEM_WHITE_FLUTE              58
#define ITEM_BERRY_JUICE              59
#define ITEM_SACRED_ASH               60
#define ITEM_SHOAL_SALT               61
#define ITEM_SHOAL_SHELL              62
#define ITEM_RED_SHARD                63
#define ITEM_BLUE_SHARD               64
#define ITEM_YELLOW_SHARD             65
#define ITEM_GREEN_SHARD              66
#define ITEM_HP_UP                    67
#define ITEM_PROTEIN                  68
#define ITEM_IRON                     69
#define ITEM_CARBOS                   70
#define ITEM_CALCIUM                  71
#define ITEM_RARE_CANDY               72
#define ITEM_PP_UP                    73
#define ITEM_ZINC                     74
#define ITEM_PP_MAX                   75
#define ITEM_GUARD_SPEC               76
#define ITEM_DIRE_HIT                 77
#define ITEM_X_ATTACK                 78
#define ITEM_X_DEFEND                 79
#define ITEM_X_SPEED                  80
#define ITEM_X_ACCURACY               81
#define ITEM_X_SPECIAL                82
#define ITEM_X_SPECIAL_DEFENSE        83
#define ITEM_POKE_DOLL                84
#define ITEM_FLUFFY_TAIL              85
#define ITEM_SUPER_REPEL              86
#define ITEM_MAX_REPEL                87
#define ITEM_ESCAPE_ROPE              88
#define ITEM_REPEL                    89
#define ITEM_SWEET_HEART              90
#define ITEM_BIG_MALASADA             91
#define ITEM_CASTELIACONE             92
#define ITEM_LUMIOSE_GALETTE          93
#define ITEM_RAGE_CANDY_BAR           94
#define ITEM_SHALOUR_SABLE            95
#define ITEM_OLD_GATEAU               96
// Evolution Items               
#define ITEM_SUN_STONE                97
#define ITEM_MOON_STONE               98
#define ITEM_FIRE_STONE               99
#define ITEM_THUNDER_STONE            100
#define ITEM_WATER_STONE              101
#define ITEM_LEAF_STONE               102
#define ITEM_DUSK_STONE               103
#define ITEM_DAWN_STONE               104
#define ITEM_SHINY_STONE              105
#define ITEM_OVAL_STONE               106
#define ITEM_ICE_STONE                107
#define ITEM_PROTECTOR                108
#define ITEM_MAGMARIZER               109
#define ITEM_PRISM_SCALE              110
#define ITEM_SACHET                   111
#define ITEM_WHIPPED_DREAM            112
#define ITEM_RAZOR_CLAW               113
#define ITEM_RAZOR_FANG               114
#define ITEM_REAPER_CLOTH             115
#define ITEM_DUBIOUS_DISC             116
#define ITEM_ELECTIRIZER              117
// Wings                         
#define ITEM_HEALTH_WING              118
#define ITEM_MUSCLE_WING              119
#define ITEM_RESIST_WING              120
#define ITEM_GENIUS_WING              121
#define ITEM_CLEVER_WING              122
#define ITEM_SWIFT_WING               123
#define ITEM_PRETTY_WING              124
// Valuable                      
#define ITEM_TINY_MUSHROOM            125
#define ITEM_BIG_MUSHROOM             126
#define ITEM_PEARL                    127
#define ITEM_BIG_PEARL                128
#define ITEM_STARDUST                 129
#define ITEM_STAR_PIECE               130
#define ITEM_NUGGET                   131
#define ITEM_HEART_SCALE              132
#define ITEM_RARE_BONE                133
#define ITEM_PEARL_STRING             134
#define ITEM_BIG_NUGGET               135
#define ITEM_COMET_SHARD              136
#define ITEM_BALM_MUSHROOM            137
// Mail                          
#define ITEM_ORANGE_MAIL              138
#define ITEM_HARBOR_MAIL              139
#define ITEM_GLITTER_MAIL             140
#define ITEM_MECH_MAIL                141
#define ITEM_WOOD_MAIL                142
#define ITEM_WAVE_MAIL                143
#define ITEM_BEAD_MAIL                144
#define ITEM_SHADOW_MAIL              145
#define ITEM_TROPIC_MAIL              146
#define ITEM_DREAM_MAIL               147
#define ITEM_FAB_MAIL                 148
#define ITEM_RETRO_MAIL               149
#define ITEM_CHERI_BERRY              150
#define ITEM_CHESTO_BERRY             151
#define ITEM_PECHA_BERRY              152
#define ITEM_RAWST_BERRY              153
#define ITEM_ASPEAR_BERRY             154
#define ITEM_LEPPA_BERRY              155
#define ITEM_ORAN_BERRY               156
#define ITEM_PERSIM_BERRY             157
#define ITEM_LUM_BERRY                158
#define ITEM_SITRUS_BERRY             159
#define ITEM_FIGY_BERRY               160
#define ITEM_WIKI_BERRY               161
#define ITEM_MAGO_BERRY               162
#define ITEM_AGUAV_BERRY              163
#define ITEM_IAPAPA_BERRY             164
#define ITEM_RAZZ_BERRY               165
#define ITEM_BLUK_BERRY               166
#define ITEM_NANAB_BERRY              167
#define ITEM_WEPEAR_BERRY             168
#define ITEM_PINAP_BERRY              169
#define ITEM_POMEG_BERRY              170
#define ITEM_KELPSY_BERRY             171
#define ITEM_QUALOT_BERRY             172
#define ITEM_HONDEW_BERRY             173
#define ITEM_GREPA_BERRY              174
#define ITEM_TAMATO_BERRY             175
#define ITEM_CORNN_BERRY              176
#define ITEM_MAGOST_BERRY             177
#define ITEM_RABUTA_BERRY             178
#define ITEM_NOMEL_BERRY              179
#define ITEM_SPELON_BERRY             180
#define ITEM_PAMTRE_BERRY             181
#define ITEM_WATMEL_BERRY             182
#define ITEM_DURIN_BERRY              183
#define ITEM_BELUE_BERRY              184
#define ITEM_LIECHI_BERRY             185
#define ITEM_GANLON_BERRY             186
#define ITEM_SALAC_BERRY              187
#define ITEM_PETAYA_BERRY             188
#define ITEM_APICOT_BERRY             189
#define ITEM_LANSAT_BERRY             190
#define ITEM_STARF_BERRY              191
#define ITEM_OCCA_BERRY               192
#define ITEM_PASSHO_BERRY             193
#define ITEM_WACAN_BERRY              194
#define ITEM_RINDO_BERRY              195
#define ITEM_YACHE_BERRY              196
#define ITEM_CHOPLE_BERRY             197
#define ITEM_KEBIA_BERRY              198
#define ITEM_SHUCA_BERRY              199
#define ITEM_COBA_BERRY               200
#define ITEM_PAYAPA_BERRY             201
#define ITEM_TANGA_BERRY              202
#define ITEM_CHARTI_BERRY             203
#define ITEM_KASIB_BERRY              204
#define ITEM_HABAN_BERRY              205
#define ITEM_COLBUR_BERRY             206
#define ITEM_BABIRI_BERRY             207
#define ITEM_CHILAN_BERRY             208
#define ITEM_MICLE_BERRY              209
#define ITEM_CUSTAP_BERRY             210
#define ITEM_JABOCA_BERRY             211
#define ITEM_ROWAP_BERRY              212
#define ITEM_ROSELI_BERRY             213
#define ITEM_KEE_BERRY                214
#define ITEM_MARANGA_BERRY            215
#define ITEM_ENIGMA_BERRY             216
// Battle                        
#define ITEM_BRIGHT_POWDER            217
#define ITEM_WHITE_HERB               218
#define ITEM_MACHO_BRACE              219
#define ITEM_EXP_SHARE                220
#define ITEM_QUICK_CLAW               221
#define ITEM_SOOTHE_BELL              222
#define ITEM_MENTAL_HERB              223
#define ITEM_CHOICE_BAND              224
#define ITEM_KINGS_ROCK               225
#define ITEM_SILVER_POWDER            226
#define ITEM_AMULET_COIN              227
#define ITEM_CLEANSE_TAG              228
#define ITEM_SOUL_DEW                 229
#define ITEM_DEEP_SEA_TOOTH           230
#define ITEM_DEEP_SEA_SCALE           231
#define ITEM_SMOKE_BALL               232
#define ITEM_EVERSTONE                233
#define ITEM_FOCUS_BAND               234
#define ITEM_LUCKY_EGG                235
#define ITEM_SCOPE_LENS               236
#define ITEM_METAL_COAT               237
#define ITEM_LEFTOVERS                238
#define ITEM_DRAGON_SCALE             239
#define ITEM_LIGHT_BALL               240
#define ITEM_SOFT_SAND                241
#define ITEM_HARD_STONE               242
#define ITEM_MIRACLE_SEED             243
#define ITEM_BLACK_GLASSES            244
#define ITEM_BLACK_BELT               245
#define ITEM_MAGNET                   246
#define ITEM_MYSTIC_WATER             247
#define ITEM_SHARP_BEAK               248
#define ITEM_POISON_BARB              249
#define ITEM_NEVER_MELT_ICE           250
#define ITEM_SPELL_TAG                251
#define ITEM_TWISTED_SPOON            252
#define ITEM_CHARCOAL                 253
#define ITEM_DRAGON_FANG              254
#define ITEM_SILK_SCARF               255
#define ITEM_UP_GRADE                 256
#define ITEM_SHELL_BELL               257
#define ITEM_SEA_INCENSE              258
#define ITEM_LAX_INCENSE              259
#define ITEM_LUCKY_PUNCH              260
#define ITEM_METAL_POWDER             261
#define ITEM_THICK_CLUB               262
#define ITEM_STICK                    263
#define ITEM_ADAMANT_ORB              264
#define ITEM_LUSTROUS_ORB             265
#define ITEM_GRISEOUS_ORB             266
#define ITEM_EXPERT_BELT              267
#define ITEM_POWER_HERB               268
#define ITEM_WIDE_LENS                269
#define ITEM_ZOOM_LENS                270
#define ITEM_DESTINY_KNOT             271
#define ITEM_SMOOTH_ROCK              272
#define ITEM_DAMP_ROCK                273
#define ITEM_HEAT_ROCK                274
#define ITEM_ICY_ROCK                 275
#define ITEM_BIG_ROOT                 276
#define ITEM_LIGHT_CLAY               277
#define ITEM_SAFETY_GOGGLES           278
#define ITEM_ROCKY_HELMET             279
#define ITEM_WEAKNESS_POLICY          280
#define ITEM_ASSAULT_VEST             281
#define ITEM_EVIOLITE                 282
#define ITEM_ABSORB_BULB              283
#define ITEM_AIR_BALLOON              284
#define ITEM_ADRENALINE_ORB           285
#define ITEM_BINDING_BAND             286
#define ITEM_CELL_BATTERY             287
#define ITEM_EJECT_BUTTON             288
#define ITEM_FLOAT_STONE              289
#define ITEM_FOCUS_SASH               290
#define ITEM_GRIP_CLAW                291
#define ITEM_IRON_BALL                292
#define ITEM_LAGGING_TAIL             293
#define ITEM_LUMINOUS_MOSS            294
#define ITEM_QUICK_POWDER             295
#define ITEM_METRONOME                296
#define ITEM_MUSCLE_BAND              297
#define ITEM_PROTECTIVE_PADS          298
#define ITEM_RED_CARD                 299
#define ITEM_RING_TARGET              300
#define ITEM_SHED_SHELL               301
#define ITEM_SNOWBALL                 302
#define ITEM_STICKY_BARB              303
#define ITEM_TERRAIN_EXTENDER         304
#define ITEM_WISE_GLASSES             305
#define ITEM_ELECTRIC_SEED            306
#define ITEM_GRASSY_SEED              307
#define ITEM_MISTY_SEED               308
#define ITEM_PSYCHIC_SEED             309
#define ITEM_LIFE_ORB                 310
#define ITEM_TOXIC_ORB                311
#define ITEM_FLAME_ORB                312
#define ITEM_BLACK_SLUDGE             313
#define ITEM_CHOICE_SPECS             314
#define ITEM_CHOICE_SCARF             315
#define ITEM_EJECT_PACK               316
#define ITEM_ROOM_SERVICE             317
#define ITEM_BLUNDER_POLICY           318
#define ITEM_HEAVY_DUTY_BOOTS         319
#define ITEM_UTILITY_UMBRELLA         320
#define ITEM_THROAT_SPRAY             321
// Key                           
#define ITEM_RED_SCARF                322
#define ITEM_BLUE_SCARF               323
#define ITEM_PINK_SCARF               324
#define ITEM_GREEN_SCARF              325
#define ITEM_YELLOW_SCARF             326
#define ITEM_MACH_BIKE                327
#define ITEM_COIN_CASE                328
#define ITEM_ITEMFINDER               329
#define ITEM_OLD_ROD                  330
#define ITEM_GOOD_ROD                 331
#define ITEM_SUPER_ROD                332
#define ITEM_SS_TICKET                333
#define ITEM_CONTEST_PASS             334
#define ITEM_WAILMER_PAIL             335
#define ITEM_DEVON_GOODS              336
#define ITEM_SOOT_SACK                337
#define ITEM_BASEMENT_KEY             338
#define ITEM_ACRO_BIKE                339
#define ITEM_POKEBLOCK_CASE           340
#define ITEM_LETTER                   341
#define ITEM_EON_TICKET               342
#define ITEM_RED_ORB                  343
#define ITEM_BLUE_ORB                 344
#define ITEM_SCANNER                  345
#define ITEM_GO_GOGGLES               346
#define ITEM_METEORITE                347
#define ITEM_ROOM_1_KEY               348
#define ITEM_ROOM_2_KEY               349
#define ITEM_ROOM_4_KEY               350
#define ITEM_ROOM_6_KEY               351
#define ITEM_STORAGE_KEY              352
#define ITEM_ROOT_FOSSIL              353
#define ITEM_CLAW_FOSSIL              354
#define ITEM_DEVON_SCOPE              355
// TmHm                          
#define ITEM_TM01                     356
#define ITEM_TM02                     357
#define ITEM_TM03                     358
#define ITEM_TM04                     359
#define ITEM_TM05                     360
#define ITEM_TM06                     361
#define ITEM_TM07                     362
#define ITEM_TM08                     363
#define ITEM_TM09                     364
#define ITEM_TM10                     365
#define ITEM_TM11                     366
#define ITEM_TM12                     367
#define ITEM_TM13                     368
#define ITEM_TM14                     369
#define ITEM_TM15                     370
#define ITEM_TM16                     371
#define ITEM_TM17                     372
#define ITEM_TM18                     373
#define ITEM_TM19                     374
#define ITEM_TM20                     375
#define ITEM_TM21                     376
#define ITEM_TM22                     377
#define ITEM_TM23                     378
#define ITEM_TM24                     379
#define ITEM_TM25                     380
#define ITEM_TM26                     381
#define ITEM_TM27                     382
#define ITEM_TM28                     383
#define ITEM_TM29                     384
#define ITEM_TM30                     385
#define ITEM_TM31                     386
#define ITEM_TM32                     387
#define ITEM_TM33                     388
#define ITEM_TM34                     389
#define ITEM_TM35                     390
#define ITEM_TM36                     391
#define ITEM_TM37                     392
#define ITEM_TM38                     393
#define ITEM_TM39                     394
#define ITEM_TM40                     395
#define ITEM_TM41                     396
#define ITEM_TM42                     397
#define ITEM_TM43                     398
#define ITEM_TM44                     399
#define ITEM_TM45                     400
#define ITEM_TM46                     401
#define ITEM_TM47                     402
#define ITEM_TM48                     403
#define ITEM_TM49                     404
#define ITEM_TM50                     405
#define ITEM_TM51                     406
#define ITEM_TM52                     407
#define ITEM_TM53                     408
#define ITEM_TM54                     409
#define ITEM_TM55                     410
#define ITEM_TM56                     411
#define ITEM_TM57                     412
#define ITEM_TM58                     413
#define ITEM_TM59                     414
#define ITEM_TM60                     415
#define ITEM_TM61                     416
#define ITEM_TM62                     417
#define ITEM_TM63                     418
#define ITEM_TM64                     419
#define ITEM_TM65                     420
#define ITEM_TM66                     421
#define ITEM_TM67                     422
#define ITEM_TM68                     423
#define ITEM_TM69                     424
#define ITEM_TM70                     425
#define ITEM_TM71                     426
#define ITEM_TM72                     427
#define ITEM_TM73                     428
#define ITEM_TM74                     429
#define ITEM_TM75                     430
#define ITEM_TM76                     431
#define ITEM_TM77                     432
#define ITEM_TM78                     433
#define ITEM_TM79                     434
#define ITEM_TM80                     435
#define ITEM_TM81                     436
#define ITEM_TM82                     437
#define ITEM_TM83                     438
#define ITEM_TM84                     439
#define ITEM_TM85                     440
#define ITEM_TM86                     441
#define ITEM_TM87                     442
#define ITEM_TM88                     443
#define ITEM_TM89                     444
#define ITEM_TM90                     445
#define ITEM_TM91                     446
#define ITEM_TM92                     447
#define ITEM_TM93                     448
#define ITEM_TM94                     449
#define ITEM_TM95                     450
#define ITEM_TM96                     451
#define ITEM_TM97                     452
#define ITEM_TM98                     453
#define ITEM_TM99                     454
#define ITEM_TM100                    455
#define ITEM_HM01                     456
#define ITEM_HM02                     457
#define ITEM_HM03                     458
#define ITEM_HM04                     459
#define ITEM_HM05                     460
#define ITEM_HM06                     461
#define ITEM_HM07                     462
#define ITEM_HM08                     463

#define ITEM_FIRST_TM           ITEM_TM01
#define ITEM_LAST_TM            ITEM_TM100
#define ITEM_TMHM_END           ITEM_HM08
#define NUM_TECHNICAL_MACHINES  100
#define NUM_HIDDEN_MACHINES     8
#define NUM_TMHMS               NUM_TECHNICAL_MACHINES + NUM_HIDDEN_MACHINES
#define REUSABLE_TMS        //comment this line out to have tms be consumable

// FireRed/LeafGreen
#define ITEM_OAKS_PARCEL    ITEM_TMHM_END + 1
#define ITEM_POKE_FLUTE     ITEM_TMHM_END + 2
#define ITEM_SECRET_KEY     ITEM_TMHM_END + 3
#define ITEM_BIKE_VOUCHER   ITEM_TMHM_END + 4
#define ITEM_GOLD_TEETH     ITEM_TMHM_END + 5
#define ITEM_OLD_AMBER      ITEM_TMHM_END + 6
#define ITEM_CARD_KEY       ITEM_TMHM_END + 7
#define ITEM_LIFT_KEY       ITEM_TMHM_END + 8
#define ITEM_HELIX_FOSSIL   ITEM_TMHM_END + 9
#define ITEM_DOME_FOSSIL    ITEM_TMHM_END + 10
#define ITEM_SILPH_SCOPE    ITEM_TMHM_END + 11
#define ITEM_BICYCLE        ITEM_TMHM_END + 12
#define ITEM_TOWN_MAP       ITEM_TMHM_END + 13
#define ITEM_VS_SEEKER      ITEM_TMHM_END + 14
#define ITEM_FAME_CHECKER   ITEM_TMHM_END + 15
#define ITEM_TM_CASE        ITEM_TMHM_END + 16
#define ITEM_BERRY_POUCH    ITEM_TMHM_END + 17
#define ITEM_TEACHY_TV      ITEM_TMHM_END + 18
#define ITEM_TRI_PASS       ITEM_TMHM_END + 19
#define ITEM_RAINBOW_PASS   ITEM_TMHM_END + 20
#define ITEM_TEA            ITEM_TMHM_END + 21
#define ITEM_MYSTIC_TICKET  ITEM_TMHM_END + 22
#define ITEM_AURORA_TICKET  ITEM_TMHM_END + 23
#define ITEM_POWDER_JAR     ITEM_TMHM_END + 24    
#define ITEM_RUBY           ITEM_TMHM_END + 25
#define ITEM_SAPPHIRE       ITEM_TMHM_END + 26

#define ITEM_N_A            ITEM_TMHM_END + 27

// Emerald
#define ITEM_MAGMA_EMBLEM   ITEM_TMHM_END + 28
#define ITEM_OLD_SEA_MAP    ITEM_TMHM_END + 29


#define ITEM_TM01_WORK_UP           ITEM_TM01
#define ITEM_TM02_DRAGON_CLAW       ITEM_TM02
#define ITEM_TM03_PSYSHOCK          ITEM_TM03
#define ITEM_TM04_CALM_MIND         ITEM_TM04
#define ITEM_TM05_ROAR              ITEM_TM05
#define ITEM_TM06_TOXIC             ITEM_TM06
#define ITEM_TM07_HAIL              ITEM_TM07
#define ITEM_TM08_BULK_UP           ITEM_TM08
#define ITEM_TM09_VENOSHOCK         ITEM_TM09
#define ITEM_TM10_HIDDEN_POWER      ITEM_TM10
#define ITEM_TM11_SUNNY_DAY         ITEM_TM11
#define ITEM_TM12_TAUNT             ITEM_TM12
#define ITEM_TM13_ICE_BEAM          ITEM_TM13
#define ITEM_TM14_BLIZZARD          ITEM_TM14
#define ITEM_TM15_HYPER_BEAM        ITEM_TM15
#define ITEM_TM16_LIGHT_SCREEN      ITEM_TM16
#define ITEM_TM17_PROTECT           ITEM_TM17
#define ITEM_TM18_RAIN_DANCE        ITEM_TM18
#define ITEM_TM19_ROOST             ITEM_TM19
#define ITEM_TM20_SAFEGUARD         ITEM_TM20
#define ITEM_TM21_FRUSTRATION       ITEM_TM21
#define ITEM_TM22_SOLAR_BEAM        ITEM_TM22
#define ITEM_TM23_SMACK_DOWN        ITEM_TM23
#define ITEM_TM24_THUNDERBOLT       ITEM_TM24
#define ITEM_TM25_THUNDER           ITEM_TM25
#define ITEM_TM26_EARTHQUAKE        ITEM_TM26
#define ITEM_TM27_RETURN            ITEM_TM27
#define ITEM_TM28_LEECH_LIFE        ITEM_TM28
#define ITEM_TM29_PSYCHIC           ITEM_TM29
#define ITEM_TM30_SHADOW_BALL       ITEM_TM30
#define ITEM_TM31_BRICK_BREAK       ITEM_TM31
#define ITEM_TM32_DOUBLE_TEAM       ITEM_TM32
#define ITEM_TM33_REFLECT           ITEM_TM33
#define ITEM_TM34_SLUDGE_WAVE       ITEM_TM34
#define ITEM_TM35_FLAMETHROWER      ITEM_TM35
#define ITEM_TM36_SLUDGE_BOMB       ITEM_TM36
#define ITEM_TM37_SANDSTORM         ITEM_TM37
#define ITEM_TM38_FIRE_BLAST        ITEM_TM38
#define ITEM_TM39_ROCK_TOMB         ITEM_TM39
#define ITEM_TM40_AERIAL_ACE        ITEM_TM40
#define ITEM_TM41_TORMENT           ITEM_TM41
#define ITEM_TM42_FACADE            ITEM_TM42
#define ITEM_TM43_FLAME_CHARGE      ITEM_TM43
#define ITEM_TM44_REST              ITEM_TM44
#define ITEM_TM45_ATTRACT           ITEM_TM45
#define ITEM_TM46_THIEF             ITEM_TM46
#define ITEM_TM47_LOW_SWEEP         ITEM_TM47
#define ITEM_TM48_ROUND             ITEM_TM48
#define ITEM_TM49_ECHOED_VOICE      ITEM_TM49
#define ITEM_TM50_OVERHEAT          ITEM_TM50
#define ITEM_TM51_STEEL_WING        ITEM_TM51
#define ITEM_TM52_FOCUS_BLAST       ITEM_TM52
#define ITEM_TM53_ENERGY_BALL       ITEM_TM53
#define ITEM_TM54_FALSE_SWIPE       ITEM_TM54
#define ITEM_TM55_SCALD             ITEM_TM55
#define ITEM_TM56_FLING             ITEM_TM56
#define ITEM_TM57_CHARGE_BEAM       ITEM_TM57
#define ITEM_TM58_SKY_DROP          ITEM_TM58
#define ITEM_TM59_BRUTAL_SWING      ITEM_TM59
#define ITEM_TM60_QUASH             ITEM_TM60
#define ITEM_TM61_WILL_O_WISP       ITEM_TM61
#define ITEM_TM62_ACROBATICS        ITEM_TM62
#define ITEM_TM63_EMBARGO           ITEM_TM63
#define ITEM_TM64_EXPLOSION         ITEM_TM64
#define ITEM_TM65_SHADOW_CLAW       ITEM_TM65
#define ITEM_TM66_PAYBACK           ITEM_TM66
#define ITEM_TM67_SMART_STRIKE      ITEM_TM67
#define ITEM_TM68_GIGA_IMPACT       ITEM_TM68
#define ITEM_TM69_ROCK_POLISH       ITEM_TM69
#define ITEM_TM70_AURORA_VEIL       ITEM_TM70
#define ITEM_TM71_STONE_EDGE        ITEM_TM71
#define ITEM_TM72_VOLT_SWITCH       ITEM_TM72
#define ITEM_TM73_THUNDER_WAVE      ITEM_TM73
#define ITEM_TM74_GYRO_BALL         ITEM_TM74
#define ITEM_TM75_SWORDS_DANCE      ITEM_TM75
#define ITEM_TM76_FLY               ITEM_TM76
#define ITEM_TM77_PSYCH_UP          ITEM_TM77
#define ITEM_TM78_BULLDOZE          ITEM_TM78
#define ITEM_TM79_FROST_BREATH      ITEM_TM79
#define ITEM_TM80_ROCK_SLIDE        ITEM_TM80
#define ITEM_TM81_X_SCISSOR         ITEM_TM81
#define ITEM_TM82_DRAGON_TAIL       ITEM_TM82
#define ITEM_TM83_INFESTATION       ITEM_TM83
#define ITEM_TM84_POISON_JAB        ITEM_TM84
#define ITEM_TM85_DREAM_EATER       ITEM_TM85
#define ITEM_TM86_GRASS_KNOT        ITEM_TM86
#define ITEM_TM87_SWAGGER           ITEM_TM87
#define ITEM_TM88_SLEEP_TALK        ITEM_TM88
#define ITEM_TM89_U_TURN            ITEM_TM89
#define ITEM_TM90_SUBSTITUTE        ITEM_TM90
#define ITEM_TM91_FLASH_CANNON      ITEM_TM91
#define ITEM_TM92_TRICK_ROOM        ITEM_TM92
#define ITEM_TM93_WILD_CHARGE       ITEM_TM93
#define ITEM_TM94_SURF              ITEM_TM94
#define ITEM_TM95_SNARL             ITEM_TM95
#define ITEM_TM96_NATURE_POWER      ITEM_TM96
#define ITEM_TM97_DARK_PULSE        ITEM_TM97
#define ITEM_TM98_WATERFALL         ITEM_TM98
#define ITEM_TM99_DAZZLING_GLEAM    ITEM_TM99
#define ITEM_TM100_CONFIDE          ITEM_TM100
#define ITEM_HM01_CUT               ITEM_HM01
#define ITEM_HM02_FLY               ITEM_HM02
#define ITEM_HM03_SURF              ITEM_HM03
#define ITEM_HM04_STRENGTH          ITEM_HM04
#define ITEM_HM05_FLASH             ITEM_HM05
#define ITEM_HM06_ROCK_SMASH        ITEM_HM06
#define ITEM_HM07_WATERFALL         ITEM_HM07
#define ITEM_HM08_DIVE              ITEM_HM08

#define FIRST_BERRY_INDEX ITEM_CHERI_BERRY
#define LAST_BERRY_INDEX ITEM_ENIGMA_BERRY
#define ITEM_TO_BERRY(itemId)(((itemId - FIRST_BERRY_INDEX) + 1))

// Check if the item is one that can be used on a Pokemon.
#define IS_POKEMON_ITEM(item) ((item) >= ITEM_POTION && (item) <= ITEM_ENIGMA_BERRY)

#endif  // GUARD_CONSTANTS_ITEMS_H
